import "./init.js";
import { generateCube, generateMatCapSphere, generateDoor } from "./create.js";
import "./debug";
generateCube();
generateCube();
generateCube();
generateCube();
generateCube();
generateMatCapSphere();
generateDoor();
console.log("generateCube");
