import "./init.js";
import { generateCube, generateMatCapSphere, generateDoor, generateEnvSphere } from "./create.js";
import "./debug";
generateCube();
generateCube();
generateCube();
generateCube();
generateCube();
generateMatCapSphere();
generateEnvSphere();
generateDoor();
console.log("generateCube");
